command:
  - streamlit
  - run
  - streamlit_app/app.py
  - --server.port=8000
  - --server.address=0.0.0.0
  - --server.enableCORS=false
  - --server.enableXsrfProtection=false
  - --server.headless=true

python:
  requirements: streamlit_app/requirements.txt

env:
  - name: DB_CATALOG
    value: "ashraf"
  - name: DB_SCHEMA
    value: "default"
  - name: DB_HOST
    value: "adb-3438839487639471.11.azuredatabricks.net"
  - name: DB_HTTP_PATH
    value: "/sql/1.0/warehouses/a94a22f8652d85c1"
  - name: DB_TOKEN
    value: ""
