command:
  - streamlit
  - run
  - streamlit_app/app.py
  - --server.port=8080
  - --server.address=0.0.0.0
  - --server.enableCORS=false
  - --server.enableXsrfProtection=false
  - --server.headless=true

python:
  requirements: streamlit_app/requirements.txt

env:
  - name: DB_CATALOG
    value: "main"
  - name: DB_SCHEMA
    value: "default"
  - name: DB_HOST
    value: ""
  - name: DB_HTTP_PATH
    value: ""
  - name: DB_TOKEN
    value: ""
